name: Update Replay

on:
  workflow_dispatch:
    inputs:
      youtubeId:
        description: 'YouTube Video ID'
        required: true
        type: string
      startTime:
        description: 'Start time in seconds'
        required: true
        type: number

jobs:
  update-replay:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update start-replay.json
      run: |
        echo "{\"youtubeId\": \"${{ github.event.inputs.youtubeId }}\", \"startTime\": ${{ github.event.inputs.startTime }}}" > api/start-replay.json

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add api/start-replay.json
        git commit -m 'Update start-replay.json'
        git push
